# Generated by Django 3.1.13 on 2023-02-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cas_ng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxygrantingticket',
            name='session_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sessionticket',
            name='session_key',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='sessionticket',
            name='ticket',
            field=models.CharField(max_length=512),
        ),
    ]
